### ISSUE TITLE
RFC - Update for Puppet 4 API

### ISSUE THREAD

**Issue by glennsarti** [lingua-pupuli/puppet-editor-services#109]
Currently the Puppet Editor Services (PES) is using the older Puppet 3 API to load and understand puppet language constructs

> The Puppet Programming Language Specification is a specification of the Puppet Programming Language. The first published release of this specification specifies the language version 4.

[Reference](https://github.com/puppetlabs/puppet-specifications)

This RFC will describe the work to add Puppet 4 Language (AKA Rich Data Types) to PES.

### Phase 1 - Achieve Parity

https://github.com/orgs/lingua-pupuli/projects/23 is tracking this phase

- [ ] Modify PES to use the loaders in `puppet/pops/loader/*` instead of `puppet/util/autoload`
No change to any existing tests should be required.  All loaded assets will remain the same

[Ref](https://github.com/puppetlabs/puppet-specifications/blob/4e54d7a8c1e8f16c1cdbc44d4b5537c27784e7cd/language/modus-operandi.md#auto-loading)

- [ ] Update the function loading to support Puppet 4 functions

Update the sidecar protocol to prefer the Puppet 4 function structure.
    * Arity is no longer a thing
    * Function types are no longer a thing (`:rvalue` vs `:statement`)
    * Functions now have one or more call signatures
    * Functions have return types per signature
    * Functions have zero or blocks that can be yielded

[Ref](https://github.com/puppetlabs/puppet-specifications/blob/master/language/func-api.md#function-api)

     Note that function documenation will be missing

- [ ] Add function documentation, via Yard, for functions

- [ ] Add caching functionality to the function loader.

- [ ] Update the Language Server with the newer sidecar protocol but no change to functionality

- [ ] Update the Puppet Class and Defined Type loading

  * Unknown gotchas

- [ ] Update the Puppet Type loading

  * Unknown gotchas

### Phase 2 - Extend the awesomeness

- [ ] Review loading decisions.  Does it make sense to make 4+ calls to the sidecar to load information or can we group it all into one call eg.  `workspace_everything` which enumerates _everything_ about the workspace.

- [ ] Add support for loading Data Types e.g. `String`

Loader, Sidecar Protocol, e.g. `workspace_datatypes` additional actions

- [ ] Add support for loading  Tasks

Loader, Sidecar Protocol, e.g. `workspace_tasks` additional actions

- [ ] Add support for loading Plans

Loader, Sidecar Protocol, e.g. `workspace_plans` additional actions

- [ ] Add a [SignatureHelp](https://microsoft.github.io/language-server-protocol/specification#textDocument_signatureHelp) provider for functions

- [ ] Add Hover support for Datatypes

- [ ] Add autocomplete support for Datatypes, and tasks (within plans)
'

**Comment by glennsarti** [comment]
This is being tracked in https://github.com/orgs/lingua-pupuli/projects/23#card-20001838

Closing.
